# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='meters',
            field=models.ManyToManyField(through='player.Player_Meter', to='games.Meter'),
        ),
    ]
