# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='story_order',
            field=models.IntegerField(default=None),
        ),
    ]
