# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-26 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('meter_value', models.IntegerField()),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Dialogue')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Meter')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character_Type'),
        ),
    ]
